groups:
  - name: watchdog
    interval: 30s
    rules:
      - record: jenkins_poc_watchdog_heartbeat_timestamp_seconds
        expr: time()

      - record: jenkins_poc_watchdog_up
        expr: vector(1)
