{
 "title": "PoC - demo-0",
 "tags": [
  "poc",
  "bloc5"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "demo-0 up",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "up{job=\"demo-node-exporter\"}",
     "legendFormat": "up"
    }
   ]
  },
  {
   "title": "CPU utilisé (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\", instance=\"gateway.ci-cd.svc.cluster.local:9100\"}[5m])) * 100)",
     "legendFormat": "CPU %"
    }
   ]
  },
  {
   "title": "Mémoire utilisée (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=\"gateway.ci-cd.svc.cluster.local:9100\"} / node_memory_MemTotal_bytes{instance=\"gateway.ci-cd.svc.cluster.local:9100\"})) * 100",
     "legendFormat": "Mémoire %"
    }
   ]
  },
  {
   "title": "Espace disque utilisé (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "(1 - (node_filesystem_avail_bytes{instance=\"gateway.ci-cd.svc.cluster.local:9100\", fstype!~\"tmpfs|overlay\"} / node_filesystem_size_bytes{instance=\"gateway.ci-cd.svc.cluster.local:9100\", fstype!~\"tmpfs|overlay\"})) * 100",
     "legendFormat": "{{ mountpoint }}"
    }
   ]
  }
 ]
}